# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ee1462e7-2b45-4828-91cc-5b39df2cea9d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-56c8fa00-672d-449f-ba2c-52e8d2e002ab".device = "/dev/disk/by-uuid/56c8fa00-672d-449f-ba2c-52e8d2e002ab";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/BF3B-8DB4";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/56e56582-4bb3-4e12-bb44-2b6ab20a1cb6"; }
    ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
